CREATE TABLE APP.ADMINISTRATOR (
	ADMINISTRATOR_ID INTEGER NOT NULL,
	ADMINISTRATOR_USERNAME VARCHAR(255) NOT NULL,
	ADMINISTRATOR_PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY (ADMINISTRATOR_ID)
);
CREATE TABLE APP.APPLICATION (
	APPLICATION_ID INTEGER NOT NULL,
	APPLICATION_RELEASE_DATE DATE,
	APPLICATION_WEBSITE VARCHAR(255),
	APPLICATION_NAME VARCHAR(255) NOT NULL,
	APPLICATION_VERSION VARCHAR(255) NOT NULL,
	APPLICATION_PLATFORM_ID INTEGER NOT NULL,
	PRIMARY KEY (APPLICATION_ID)
);
CREATE TABLE APP.DOWNLOAD (
	DOWNLOAD_ID INTEGER NOT NULL,
	DOWNLOAD_DATE DATE NOT NULL,
	DOWNLOAD_MEMBER_ID INTEGER NOT NULL,
	DOWNLOAD_APPLICATION_ID INTEGER NOT NULL,
	PRIMARY KEY (DOWNLOAD_ID)
);
CREATE TABLE APP.MEMBER (
	MEMBER_ID INTEGER NOT NULL,
	MEMBER_LASTNAME VARCHAR(255),
	MEMBER_USERNAME VARCHAR(255) NOT NULL,
	MEMBER_EMAIL VARCHAR(255) NOT NULL,
	MEMBER_BIRTHDATE DATE,
	MEMBER_FIRSTNAME VARCHAR(255) NOT NULL,
	MEMBER_PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY (MEMBER_ID)
);
CREATE TABLE APP.PLATFORM (
	PLATFORM_ID INTEGER NOT NULL,
	PLATFORM_NAME VARCHAR(255) NOT NULL,
	PLATFORM_VERSION VARCHAR(255) NOT NULL,
	PRIMARY KEY (PLATFORM_ID)
);
CREATE TABLE APP.SEQUENCE (
	SEQ_NAME VARCHAR(50) NOT NULL,
	SEQ_COUNT DECIMAL(15),
	PRIMARY KEY (SEQ_NAME)
);

ALTER TABLE APP.APPLICATION
	ADD FOREIGN KEY (APPLICATION_PLATFORM_ID) 
	REFERENCES APP.PLATFORM (PLATFORM_ID);


ALTER TABLE APP.DOWNLOAD
	ADD FOREIGN KEY (DOWNLOAD_APPLICATION_ID) 
	REFERENCES APP.APPLICATION (APPLICATION_ID);

ALTER TABLE APP.DOWNLOAD
	ADD FOREIGN KEY (DOWNLOAD_MEMBER_ID) 
	REFERENCES APP.MEMBER (MEMBER_ID);


